# Deployment pipeline for beta.helikuparinen.fi

name: Beta deployment pipeline

on:
    push:
        branches:
            - staging
    pull_request:
        branches: [staging]
        types: [opened, synchronize]

jobs:
    main-deploy_pipeline_beta:
        runs-on: ubuntu-18.04
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: '18.x'
            - name: npm install
              run: npm install --legacy-peer-deps
            - name: lint
              run: npm run lint
            - name: npm run build
              run: npm run build
              env:
                  SPACE_ID: ${{ secrets.SPACE_ID }}
                  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                  PREVIEW_ACCESS_TOKEN: ${{ secrets.PREVIEW_ACCESS_TOKEN }}
            - name: Deploy
              if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message), '#skip') }}
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SSH_HOST }}
                  USERNAME: ${{ secrets.SSH_USER }}
                  KEY: ${{ secrets.SSH_KEY }}
                  PORT: ${{ secrets.SSH_PORT }}
                  script: |
                      cd ./beta.helikuparinen.fi
                      NODE_ENV=beta
                      sh ./deploy.sh
            - uses: actions/checkout@v2
            - name: Bump version and push tag
              if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message), '#skip') }}
              uses: anothrNick/github-tag-action@eca2b69f9e2c24be7decccd0f15fdb1ea5906598 # let's use a hash version
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
